package rules
import com.bcm.entity.*
import com.bcm.entity.DrlResult//可以导入类，静态方法

rule "rule0003"

no-loop true
when
       $person : Person ( age >20)
       $car : Car( age > 15)
    then
        DrlResult   result1= new DrlResult();
        result1.setStaute("true");
        result1.setKey("rule0003");
        $car.setDiscount(80);
        $person.setName("唐三");
        result1.setCar($car);
        result1.setPerson($person);
        insert(result1);
        System.out.println("rule0003规则触发");

end