server:
  port: 8080
spring:
#  #数据库驱动
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql:///spring?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
#    username: root
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
  #jpa 的建表操作
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       format_sql: true